version: '3.9'

services:
  postgres:
    build: docker/postgres/.
    environment:
      POSTGRES_DB: 'trip_app_db'
      POSTGRES_USER: 'Anubis'
      POSTGRES_PASSWORD: '123'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trip_app_network

  redis:
    image: redis:latest
    networks:
      - trip_app_network

  django:
    build: ./technical_test
    command: sh -c "python manage.py runserver 0.0.0.0:8000 & celery -A technical_test.celery worker -l info"
    #command: sleep infinity
    volumes:
      - ./technical_test:/app
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    networks:
      - trip_app_network

volumes:
  postgres_data:

networks:
  trip_app_network:
    driver: bridge
