# Generated by Django 4.1 on 2024-09-02 23:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("no_trip", "No Trip"),
                            ("waiting", "Waiting"),
                            ("on_trip", "On_trip"),
                            ("arrived", "Arrived"),
                        ],
                        default="no_trip",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="passenger",
            index=models.Index(fields=["location"], name="location_idx"),
        ),
    ]
