# Generated by Django 4.2.16 on 2024-09-04 12:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_cityboundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityboundary',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
