# Generated by Django 4.2.16 on 2024-09-04 15:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_cityboundary_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
