# Generated by Django 4.1 on 2024-09-02 23:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("car", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("on_trip", "On Trip"),
                            ("occupied", "Occupied"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(fields=["location"], name="location_idx_driver"),
        ),
    ]
